version: "3"
services: 
    site:
        image: postgres
        container_name: "pg_container"
        restart: always
        environment: 
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=test_db
        ports: 
            - "5432:5432"
        volumes: 
            - "./db:/var/lib/postgresql/how_data/"

    bi:
        image: metabase/metabase
        ports:
            - "3000:3000"
        links:
            - site


